### ISSUE TITLE
Git only or TFVS too?

### ISSUE THREAD

**Issue by xperiandri** [bymyslf/Bymyslf.NupkgPolicy#1]
Is it Git only? Or it does not allow check into TFVC repositories too?
If so does it have separate settings for Git and TFVC?

**Comment by bymyslf** [comment]
Hi,

this is only for TFVC.

You can download it from here: https://visualstudiogallery.msdn.microsoft.com/6a2906d1-c876-4085-98d2-623c2e9d307e
